sudo: required
language: generic
services: docker

addons:
  artifacts: true

before_install:
  - chmod +x compile_with_tectonic.sh

script:
  # Builds are available at https://travis-ci.com/RIT-Space-Exploration/SPEX-Project-Definition-Documents
  - make all

branches:
  only:
  - master
  - travis-ci
