# Edit this file to automatically compile your TeX file as a PDF.
# Specify the directory containing the document to compile as BUILD_DIRECTORY
# Specify the root TeX file to use for the build as TEX_MAIN (with relative path from BUILD_DIRECTORY)
#
# Builds are available at https://travis-ci.com/RIT-Space-Exploration/SPEX-Project-Definition-Documents
# FOR CONVENIENCE ONLY. DO NOT INCLUDE THIS FILE IN YOUR COMMITS OR PULL REQUEST.
#
# Thanks to github.com/PHPirates/travis-ci-latex-pdf for providing this boilerplate file.
env:
  - BUILD_DIRECTORY=COPY_THIS/
  - TEX_MAIN=SPEXpdd

language: generic

install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.10;
    fi

cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic

script: 
  # Change working directory to the directory containing the document to build.
 - cd $BUILD_DIRECTORY
 # Build with the recipe "tectonic ➞ bibtex ➞ tectonic × 2".
 - tectonic --keep-intermediates --reruns 0 $(TEX_MAIN).tex
 # If a bib file exists run bitex to compile references
 - if [ -f "*.bib" ]; then bibtex $TEX_MAIN; fi
 # Final 2x runs of tectonic to create output PDF
 - tectonic $(TEX_MAIN).tex --print
 # Change the working directory back to home.
 - cd ../