sudo: required
language: generic
services: docker

addons:
  artifacts: true

before_install:
  - chmod +x compile_with_tectonic.sh

script:
  # Builds are available at https://travis-ci.com/RIT-Space-Exploration/SPEX-Project-Definition-Documents
  - make all

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  file:
    - "**.pdf"
  skip_cleanup: true
  draft: true

branches:
  only:
  - master
  - travis-ci
