sudo: required
language: generic
services: docker

branches:
  only:
    - master
    - travis-ci

stages:
  - compile
  - deploy

jobs:
  include:
    - stage: compile
      script: 
        - chmod +x compile_with_tectonic.sh
        - make all
    - stage: deploy
      before_deploy:
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        file:
          - "**.pdf"
        skip_cleanup: true
        draft: true
