sudo: required
language: generic
services: docker

script:
  # Builds are available at https://travis-ci.com/RIT-Space-Exploration/SPEX-Project-Definition-Documents
  - compile_with_tectonic "COPY_THIS" "SPEXpdd"